################################################################
#
# $Id:$
#
# $Log:$
#
CC = m68k-atari-mint-gcc

CFLAGS=-O3 -Wall -DNORMALUNIX -DLINUX -D__BIG_ENDIAN__ -DUSEASM -std=c99 -fasm
# -mfastcall with the filter-out below builds, but immedialy crashes :-(
#CFLAGS=-O3 -Wall -DNORMALUNIX -DLINUX -D__BIG_ENDIAN__ -DUSEASM -mfastcall -std=c99 -fasm
CFLAGS20=$(CFLAGS) -m68020-60 -mtune=68020 -msoft-float
CFLAGS2F=$(CFLAGS) -m68020-60 -mtune=68020 -m68881
LDFLAGS= -Wl,-Map=$@.map
LDLIBS=./deps/68000.soft-float.fastcall/libm.a
LDLIBS20=./deps/68020-60.soft-float.fastcall/libm.a
LDLIBS2F=./deps/68020-60.68881.fastcall/libm.a

# subdirectory for objects
O=atari

# not too sophisticated dependency
OBJS=				\
		$(O)/atari_c2p.o		\
		$(O)/atari_checkcpu.o	\
		$(O)/atari_ym.o		\
		$(O)/doomdef.o		\
		$(O)/doomstat.o		\
		$(O)/dstrings.o		\
		$(O)/i_system.o		\
		$(O)/i_sound.o		\
		$(O)/i_video.o		\
		$(O)/i_net.o			\
		$(O)/tables.o			\
		$(O)/f_finale.o		\
		$(O)/f_wipe.o 		\
		$(O)/d_main.o			\
		$(O)/d_net.o			\
		$(O)/d_items.o		\
		$(O)/g_game.o			\
		$(O)/m_menu.o			\
		$(O)/m_misc.o			\
		$(O)/m_argv.o  		\
		$(O)/m_bbox.o			\
		$(O)/m_fixed.o		\
		$(O)/m_swap.o			\
		$(O)/m_cheat.o		\
		$(O)/m_random.o		\
		$(O)/am_map.o			\
		$(O)/p_ceilng.o		\
		$(O)/p_doors.o		\
		$(O)/p_enemy.o		\
		$(O)/p_floor.o		\
		$(O)/p_inter.o		\
		$(O)/p_lights.o		\
		$(O)/p_map.o			\
		$(O)/p_maputl.o		\
		$(O)/p_plats.o		\
		$(O)/p_pspr.o			\
		$(O)/p_setup.o		\
		$(O)/p_sight.o		\
		$(O)/p_spec.o			\
		$(O)/p_switch.o		\
		$(O)/p_mobj.o			\
		$(O)/p_telept.o		\
		$(O)/p_tick.o			\
		$(O)/p_saveg.o		\
		$(O)/p_user.o			\
		$(O)/r_bsp.o			\
		$(O)/r_data.o			\
		$(O)/r_draw.o			\
		$(O)/r_main.o			\
		$(O)/r_plane.o		\
		$(O)/r_segs.o			\
		$(O)/r_sky.o			\
		$(O)/r_things.o		\
		$(O)/w_wad.o			\
		$(O)/wi_stuff.o		\
		$(O)/v_video.o		\
		$(O)/st_lib.o			\
		$(O)/st_stuff.o		\
		$(O)/hu_stuff.o		\
		$(O)/hu_lib.o			\
		$(O)/s_sound.o		\
		$(O)/z_zone.o			\
		$(O)/info.o				\
		$(O)/sounds.o		\
		$(O)/i_main.o
OBJS20=$(OBJS:%.o=%.20.o)
OBJS2F=$(OBJS:%.o=%.2f.o)

all:	 $(O)/stdoom.tos $(O)/stdoom20.tos $(O)/stdoom2f.tos

clean:
	rm -f $(O)/stdoom.tos $(O)/stdoom20.tos $(O)/stdoom2f.tos $(O)/*.o $(O)/*.map

$(O)/stdoom.tos:	$(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDLIBS)
#	$(CC) $(filter-out -mfastcall,$(CFLAGS)) $(OBJS) -o $@ $(LDLIBS)

$(O)/stdoom20.tos:	$(OBJS20)
	$(CC) $(CFLAGS20) $(OBJS20) -o $@ $(LDLIBS20)
#	$(CC) $(filter-out -mfastcall,$(CFLAGS20)) $(OBJS20) -o $@ $(LDLIBS20)

$(O)/stdoom2f.tos:	$(OBJS2F)
	$(CC) $(CFLAGS2F) $(OBJS2F) -o $@ $(LDLIBS2F)
#	$(CC) $(filter-out -mfastcall,$(CFLAGS2F)) $(OBJS2F) -o $@ $(LDLIBS2F)

$(O)/%.2f.o:	%.c
	$(CC) $(CPPFLAGS) $(CFLAGS2F) -c $< -o $@

$(O)/%.20.o:	%.c
	$(CC) $(CPPFLAGS) $(CFLAGS20) -c $< -o $@

$(O)/%.o:	%.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

# Rule for compiling to assembly on demand
$(O)/%.2f.s: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS2F) -c $< -S -fverbose-asm -o $@
$(O)/%.20.s: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS20) -c $< -S -fverbose-asm -o $@
$(O)/%.s: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -S -fverbose-asm -o $@

#############################################################
#
#############################################################
